### ISSUE TITLE
Где

### ISSUE THREAD

**Issue by jiggaaut** [OnceDoter/elcomplus#1]
https://github.com/OnceDoter/elcomplus/blob/eaccbdff234f9b5a8ca0b52e57e94a0072719469/src/Infrastructure/TreeViewExtensions.cs#L28

**Comment by OnceDoter** [comment]
что

**Comment by jiggaaut** [comment]
трайкача

**Comment by OnceDoter** [comment]
![image](https://user-images.githubusercontent.com/53345093/95299259-99edef00-08a7-11eb-92ba-2a302d41baaa.png)
ArgumentNullException и WebException ловятся еще здесь Uri.IsWellFormedUriString в классе формы
NotSupportedException не возможен в моем коде:)

**Comment by OnceDoter** [comment]
=> трайкеча не нужна

**Comment by jiggaaut** [comment]
ладно..
